spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/spring_project?useSSL=false
        username: root
        password: toptuda
        
    jpa:
        hibernate:
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
            
    thymeleaf:
        cache: false